# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: paper_search/v1/paper_search.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 3, "", "paper_search/v1/paper_search.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n"paper_search/v1/paper_search.proto\x12\x0fpaper_search.v1"S\n\x05Paper\x12\x14\n\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n\x08\x61\x62stract\x18\x02 \x01(\tR\x08\x61\x62stract\x12\x18\n\x07\x61uthors\x18\x03 \x03(\tR\x07\x61uthors"K\n\x12SearchPaperRequest\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n\x0bnum_results\x18\x02 \x01(\x05R\nnumResults"E\n\x13SearchPaperResponse\x12.\n\x06papers\x18\x01 \x03(\x0b\x32\x16.paper_search.v1.PaperR\x06papers"0\n\x18QueryAugmentationRequest\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query"-\n\x19QueryAugmentationResponse\x12\x10\n\x03res\x18\x01 \x01(\tR\x03res2\xda\x01\n\x12PaperSearchService\x12X\n\x0bSearchPaper\x12#.paper_search.v1.SearchPaperRequest\x1a$.paper_search.v1.SearchPaperResponse\x12j\n\x11QueryAugmentation\x12).paper_search.v1.QueryAugmentationRequest\x1a*.paper_search.v1.QueryAugmentationResponseB\x80\x01\n\x13\x63om.paper_search.v1B\x10PaperSearchProtoP\x01\xa2\x02\x03PXX\xaa\x02\x0ePaperSearch.V1\xca\x02\x0ePaperSearch\\V1\xe2\x02\x1aPaperSearch\\V1\\GPBMetadata\xea\x02\x0fPaperSearch::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "paper_search.v1.paper_search_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\023com.paper_search.v1B\020PaperSearchProtoP\001\242\002\003PXX\252\002\016PaperSearch.V1\312\002\016PaperSearch\\V1\342\002\032PaperSearch\\V1\\GPBMetadata\352\002\017PaperSearch::V1"
    _globals["_PAPER"]._serialized_start = 55
    _globals["_PAPER"]._serialized_end = 138
    _globals["_SEARCHPAPERREQUEST"]._serialized_start = 140
    _globals["_SEARCHPAPERREQUEST"]._serialized_end = 215
    _globals["_SEARCHPAPERRESPONSE"]._serialized_start = 217
    _globals["_SEARCHPAPERRESPONSE"]._serialized_end = 286
    _globals["_QUERYAUGMENTATIONREQUEST"]._serialized_start = 288
    _globals["_QUERYAUGMENTATIONREQUEST"]._serialized_end = 336
    _globals["_QUERYAUGMENTATIONRESPONSE"]._serialized_start = 338
    _globals["_QUERYAUGMENTATIONRESPONSE"]._serialized_end = 383
    _globals["_PAPERSEARCHSERVICE"]._serialized_start = 386
    _globals["_PAPERSEARCHSERVICE"]._serialized_end = 604
# @@protoc_insertion_point(module_scope)
