# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from paper_search.v1 import (
    paper_search_pb2 as paper__search_dot_v1_dot_paper__search__pb2,
)


class PaperSearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchPaper = channel.unary_unary(
            "/paper_search.v1.PaperSearchService/SearchPaper",
            request_serializer=paper__search_dot_v1_dot_paper__search__pb2.SearchPaperRequest.SerializeToString,
            response_deserializer=paper__search_dot_v1_dot_paper__search__pb2.SearchPaperResponse.FromString,
            _registered_method=True,
        )
        self.QueryAugmentation = channel.unary_unary(
            "/paper_search.v1.PaperSearchService/QueryAugmentation",
            request_serializer=paper__search_dot_v1_dot_paper__search__pb2.QueryAugmentationRequest.SerializeToString,
            response_deserializer=paper__search_dot_v1_dot_paper__search__pb2.QueryAugmentationResponse.FromString,
            _registered_method=True,
        )


class PaperSearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchPaper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QueryAugmentation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PaperSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SearchPaper": grpc.unary_unary_rpc_method_handler(
            servicer.SearchPaper,
            request_deserializer=paper__search_dot_v1_dot_paper__search__pb2.SearchPaperRequest.FromString,
            response_serializer=paper__search_dot_v1_dot_paper__search__pb2.SearchPaperResponse.SerializeToString,
        ),
        "QueryAugmentation": grpc.unary_unary_rpc_method_handler(
            servicer.QueryAugmentation,
            request_deserializer=paper__search_dot_v1_dot_paper__search__pb2.QueryAugmentationRequest.FromString,
            response_serializer=paper__search_dot_v1_dot_paper__search__pb2.QueryAugmentationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "paper_search.v1.PaperSearchService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "paper_search.v1.PaperSearchService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class PaperSearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchPaper(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/paper_search.v1.PaperSearchService/SearchPaper",
            paper__search_dot_v1_dot_paper__search__pb2.SearchPaperRequest.SerializeToString,
            paper__search_dot_v1_dot_paper__search__pb2.SearchPaperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def QueryAugmentation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/paper_search.v1.PaperSearchService/QueryAugmentation",
            paper__search_dot_v1_dot_paper__search__pb2.QueryAugmentationRequest.SerializeToString,
            paper__search_dot_v1_dot_paper__search__pb2.QueryAugmentationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
